### ISSUE TITLE
Problem with hidden inputs

### ISSUE THREAD

**Issue by enriquepiatti** [mathiasbynens/jquery-placeholder#104]
If the inputs are hidden, then when we show them the placeholder is not shown.
After a blur event on those inputs the placeholder became visible.

**Comment by donlion** [comment]
How far is the development of this? If someone fixed it, please push to the master :) It's a mess with custom-code in a bower-controlled-solution ;)
If not, I guess the only thing needed is an exception for hidden="hidden" and type="hidden" - I'd gladly do it

**Comment by amerikan** [comment]
In latest version `input[type=hidden]` is excluded from using placeholder.
