### ISSUE TITLE
$.val() returns placeholder value instead of empty string on IE

### ISSUE THREAD

**Issue by mmagn** [mathiasbynens/jquery-placeholder#107]
I had this issue with my code so I decided to check if everything was ok on the demo page then I encountered the same bug.

you can try it: run IE and load  http://mathiasbynens.be/demo/placeholder 

run in IE console this line : 

```javascript
$('#p').val() 
```
you should get an empty string, but instead you'll receive "e.g. hunter2", the placeholder value

When debugging the getter (line 41)

```javascript
return $element.data('placeholder-enabled') && $element.hasClass('placeholder') ? '' : element.value;
```
*$element* has no data attribute named 'placeholder-enabled', so the test is false and *element.value* is returned.

*my test configuration is IE9 / Win7*

**Comment by amerikan** [comment]
Should be fix in latest version.
