### ISSUE TITLE
Not working in IE8 with multiple forms

### ISSUE THREAD

**Issue by greendezine** [mathiasbynens/jquery-placeholder#110]
I have two forms on the page. The inputs all have existing classes. But I noticed that the placeholder class is not being added. Works fine in IE9, but not in IE8. Anyone else have this issue?

**Comment by stevedb** [comment]
I'm having an issue getting this working in ie8. The placeholder() method is called in jQuery's ready handler. I can see the inputs have attributes added to them (i.e. jQuery1102006566...=500 etc...), I'm assuming this is the placeholder plugin at work. But the placeholder text is still not appearing in the input fields. Any pointers?

**Comment by erikmontes** [comment]
@stevedb do you have a demo for me to try out? Or maybe can you paste the code here?

**Comment by shenmiweiyi** [comment]
you use web developer tool check out if have js error?

At 2015-01-30 02:11:21, "Steven Duncan-Brown" <notifications@github.com> wrote:


I'm having an issue getting this working in ie8. The placeholder() method is called in jQuery's ready handler. I can see the inputs have attributes added to them (i.e. jQuery1102006566...=500 etc...), I'm assuming this is the placeholder plugin at work. But the placeholder text is still not appearing in the input fields. Any pointers?

**Comment by stevedb** [comment]
Thanks for the replies, sorry to waste your time but this is a non issue.

I've taken over a build from someone else and I just needed to study the code harder. It works fine as directed in the documentation.

**Comment by amerikan** [comment]
I have 2 forms on a page and tested IE8 on Windows 7 with the latest version of the plugin **v2.2.0** and it works fine. Try updating to latest version of the plugin.
