### ISSUE TITLE
No placeholder and no class being set in IE8

### ISSUE THREAD

**Issue by number8pie** [mathiasbynens/jquery-placeholder#148]
If you go to http://www.f3racing.co.uk/contact.html in IE8 you'll see that the placeholder text is not showing. I've checked the source and it isn't adding the classes I've been trying to figure out what I'm doing wrong and I can't seem to get to the bottom of it.

**Comment by dnlmzw** [comment]
@erikmontes Sorry, it is such a long time ago I worked on the project I had this issue on. I just checked the code and it says 1.10.2. Others might have worked on the project after me, but I doubt they would replace the jQuery version.

**Comment by erikmontes** [comment]
I cannot reproduce this. Please update to latest version of placeholder plugin 2.1.0, if issue still persists please create an example for me to test.
