### ISSUE TITLE
Placeholder blanked out by knockout.js in IE9

### ISSUE THREAD

**Issue by magicsoft714** [mathiasbynens/jquery-placeholder#149]
I've been using your placeholder to make up for IE9's lack of support and it's been working great.  I recently decided to switch and use knockout.js to data-bind my fields instead of filling them manually using jQuery itself.  However, when I have a field where the value is an empty string, the placeholder disappears (I assume because it thinks that the empty string that knockout.js bound to the input is a valid entry).

Andrew

**Comment by trungduyvu** [comment]
This is probably the same problem. 
http://tech.pro/blog/1606/knockoutjs-input-placeholders-and-ie-oh-my

**Comment by gamesover** [comment]
What about this one: https://jsfiddle.net/ynn9abnt/2/
try to click button but placeholder is not changed in IE9
