### ISSUE TITLE
Placeholder is problematic when page loads and input is focused straight away

### ISSUE THREAD

**Issue by Jezternz** [mathiasbynens/jquery-placeholder#154]
I have a website that requires authentication, The first thing a user will ever type is the username. For this reason I automaticly focus the username field for a fast log-on. However no placeholder is displayed when focus is on the input (in IE), in Firefox and Chrome the behaviour is different (it shows the placeholder while the value is an empty ""). 

It is rather problematic in my scenario but could be problematic in any scenario where you may want to autofocus an input. Regardless it is inconsistent behavior. Was there a technical reason behind this choice? i noticed using inspector the value is set, nothing else. I guess this means the plugin would require a serious rewrite to add this feature request?

Cheers,
J

**Comment by amerikan** [comment]
This is the expected behavior. Issue #92 would solve this problem, if it gets implemented, whenever that will happen, I don't know.
