### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by feross** [mathiasbynens/jquery-placeholder#156]
Can you publish this to npm?

**Comment by feross** [comment]
@mathiasbynens Any chance of revisiting this decision? Times have changed. npm is not just for node modules anymore.

**Comment by ljharb** [comment]
Never has been, but certainly not now :-)

**Comment by Qantas94Heavy** [comment]
@feross as it seems that won't be happening for a while, would you mind pulling version 2.1.0 into your fork? Thanks! :+1:

**Comment by feross** [comment]
@Qantas94Heavy Done, 2.1.0 is published!
