### ISSUE TITLE
Placeholder not working after javascript windows.open in IE

### ISSUE THREAD

**Issue by xelon86** [mathiasbynens/jquery-placeholder#195]
Hi, in IE the placeholder is not working after window.open javascript is triggered.  My codes are as follow:
![ss1](https://f.cloud.github.com/assets/6947309/2417485/b3ac46e8-ab21-11e3-823f-e1b9f2050e4c.JPG)

**Comment by nisha-kajale** [comment]
Hi,
I am facing the same issue.
In my case i am having an export button whenever i click the export button to submit the export button and export csv. The placeholders are getting disappeared.
Kindly help with a solution.
Thanks,
Nisha
