### ISSUE TITLE
IE8 Password placeholder becomes text.

### ISSUE THREAD

**Issue by exussum12** [mathiasbynens/jquery-placeholder#196]
jsfiddle: http://jsfiddle.net/PPRa3/

The above JS fiddle shows a basic case of the problem im having.
It also uses parsley.js.

To recreate the problem. Press "Get Started" without filling in any form data, There should be some validation at the top  (saying passwords etc dont match). When clicking in to edit password, Its now a text box with the value Password* rather than a placeholder. 

Im not exactly sure what the conflict is. To test in IE 8 im using Moden.ie's VM IE8 - Win 7

**Comment by jgliesman** [comment]
Has this issue been resolved? I am still experiencing this in IE9? The type="password" is being replaced with type="text" ...

**Comment by amerikan** [comment]
Fixed in  v2.1.2. Please update it.
