### ISSUE TITLE
Override native IE10+ placeholder behavior, disappearing text on focus

### ISSUE THREAD

**Issue by danielHalan** [mathiasbynens/jquery-placeholder#204]
modern IE native placeholder feature clears the text on Focus, which isnt so good when using JS to pre-select a textbox.

Is there a way to override this behavior? if not, would be a nice feature.

**Comment by erikmontes** [comment]
I'm going to say this is related to #92

**Comment by gabskoro** [comment]
Argh, I need this feature now :)

**Comment by amerikan** [comment]
Closing, duplicate of #92
