### ISSUE TITLE
Keep placeholder class when removing input value on a blur event 

### ISSUE THREAD

**Issue by pengill** [mathiasbynens/jquery-placeholder#211]
If another event handler is attached to the input 'blur' event that clears out the input value inside it the plugin removes the 'placeholder' class unnecessary.

Example:
```html
<input type="text" name="text1" placeholder="Type something…">
```
setup a new new event handler on blur that clears the value

```js
$("input[name='text1']").on("blur", function() {
     $(this).val("");
});
```

The results of this: the placeholder value will still appear in the input but the 'placeholder' class got removed.

**Comment by xsbear** [comment]
the same issue with you

**Comment by amerikan** [comment]
Duplicate of #92
