### ISSUE TITLE
Password type inputs are focused on submit

### ISSUE THREAD

**Issue by goodforenergy** [mathiasbynens/jquery-placeholder#226]
I have a form on which I am performing client side validation on submit (so as not to progress with the submit if there are issues). I have noticed that the password type input on the form gains focus on submit in browsers where the placeholder plugin is active. You can see this briefly on your [demo page](https://mathiasbynens.be/demo/placeholder) (before the submit actually happens), but I have made a [fiddle](http://jsfiddle.net/goodforenergy/thjxq127/4/) for clarification.

Just press the submit button to reproduce the issue.

**Comment by shaneparsons** [comment]
+1

**Comment by yangkennyk** [comment]
+1 . when there are  multiple password fields, the placeholder text is filling the password input field when submitting an empty form.

**Comment by Alex1990** [comment]
I've come cross this bug and fixed it in #259. The previous **set hook** and `clearPlaceholder` are written with bugs. You can check the demo after fixing: [http://alex1990.github.io/misc/placeholder-polyfill-test/placeholder-polyfill-test.html](http://alex1990.github.io/misc/placeholder-polyfill-test/placeholder-polyfill-test.html).

**Comment by amerikan** [comment]
Should be fixed in latest version.
