### ISSUE TITLE
Fail code

### ISSUE THREAD

**Issue by ghost** [mathiasbynens/jquery-placeholder#228]
```javascript
// Clear placeholder values upon page reload
		$(window).bind('beforeunload.placeholder', function() {
			$('.placeholder').each(function() {
				this.value = '';
			});
		});
```
please review this part, i have some problems when append some of html and then use .placeholder() but it fired this park and i see placeholders after focus -> unfocus. Thanks But i comment this part and work fine. I cant understand for what it

**Comment by amerikan** [comment]
Need example code to show the issue you're speaking about.
