### ISSUE TITLE
To be compatible with parsley.js

### ISSUE THREAD

**Issue by chenshunyu** [mathiasbynens/jquery-placeholder#238]
I modified jquery.placeholder.js at line:180 like this
![image](https://cloud.githubusercontent.com/assets/10322104/5623520/8ba85862-9590-11e4-991a-a497246a4218.png)

because parsley.js will change styles of the element before the replacement of password and text

**Comment by erikmontes** [comment]
@chenshunyu are you using 2.1.0?

**Comment by chenshunyu** [comment]
@erikmontes Yes,I downloaded this version from just this website

**Comment by amerikan** [comment]
This plugin creates an invisible input text field by appending it. So it unfortunately manipulates the underlying. It is possible to target parsely, but fixing it for parsely might break it in other plugins, so there's no easy way to fix it everywhere, therefore I do not intend to fix this any time soon.
