### ISSUE TITLE
Placeholders disappear in IE9 after a refresh

### ISSUE THREAD

**Issue by OlmoAcerta** [mathiasbynens/jquery-placeholder#239]
Steps to reproduce:

```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<script src="../src/vendor/jquery/jquery-2.1.3.js"></script>
	<script src="../src/vendor/jquery-placeholder/jquery.placeholder.js"></script>
</head>
<body>
	<input type="text" placeholder="test 123">
	<script>$('input, textarea').placeholder();</script>
</body>
</html>
```

When loading the page for the first time, this works. But when I refresh, placeholders do not appear. If I click the input and click away, it reappears.

**Comment by OlmoAcerta** [comment]
I've noticed that when I comment out the "Clear placeholder values upon page reload" part of the script, the placeholder keeps working on page refresh. Why is this code needed?

(fwiw we target IE9+.)

**Comment by erikmontes** [comment]
You currently have:
```js
<script>$('input, textarea').placeholder();</script>
```

Can you try wrapping it in anonymous function so that it is only executed after DOM is ready  such as:
```js
<script>
$(function () {
    $('input, textarea').placeholder();
});
</script>
```

**Comment by WisdomPig** [comment]
why it doesn't work in IE?

**Comment by OlmoAcerta** [comment]
@erikmontes yes, that was the problem. Thank you for your help.
