### ISSUE TITLE
why it doesn't work in IE? just use the demo which you given

### ISSUE THREAD

**Issue by WisdomPig** [mathiasbynens/jquery-placeholder#240]

**Comment by erikmontes** [comment]
The demo works for me. What Windows and IE versions are you using?

**Comment by WisdomPig** [comment]
windows7 and IE9, I also test in IE-TESTER

**Comment by erikmontes** [comment]
It works fine when I try it.

![screen shot 2015-01-20 at 2 52 06 pm](https://cloud.githubusercontent.com/assets/179356/5827944/f28b7bd0-a0b3-11e4-8530-57fbdfe17854.png)
