### ISSUE TITLE
Browserify now requires Bower

### ISSUE THREAD

**Issue by lucastschmidt** [mathiasbynens/jquery-placeholder#243]
https://github.com/mathiasbynens/jquery-placeholder/pull/232

I tried to build my app today and found out it didnt work due to a ```bower install``` as a post-install-script on NPM.

Before I was requiring directly with browserify and worked no issues.

So, whats the deal with this?

**Comment by callumacrae** [comment]
Sorry, this is a jQuery plugin with a dependency on *an entire package manager*? That's pretty crazy.

The package managers are designed to handle dependencies: you shouldn't need to run `bower install`!

I would send a pull request, but I don't want to break anything and can think of no reason why you would do this. Is there a reason?

**Comment by arminrosu** [comment]
I second this request, please remove the `bower install` postinstall script. I am using npm as a dependency manager and this breaks my build (since I don't have bower installed).

**Comment by erikmontes** [comment]
Please do pull request.

**Comment by erikmontes** [comment]
@lucastschmidt @arminrosu check master branch. Close if resolved. Thanks.

**Comment by arminrosu** [comment]
@erikmontes Fix verified. Please bump the version number so npm picks up on the change.

**Comment by callumacrae** [comment]
thanks for asking for a pull request and then completely ignoring my pull request and implementing it yourself, guys

**Comment by erikmontes** [comment]
@callumacrae sorry, your PR included much more than was necessary to resolve this particular issue.

**Comment by callumacrae** [comment]
Did it add anything you didn't want?
