### ISSUE TITLE
Conflict with jquery.validate.js in IE9 

### ISSUE THREAD

**Issue by kimzhu1980** [mathiasbynens/jquery-placeholder#246]
I have tested the latest version placeholder plug-in in IE9 with latest jquery.validate.js.  All my custom validation methods are fired after I clicked the submit button, 

e.g.
<form id ="myform"/>
<input type="text" id="mobile" name="mobile" placeholder="mobile number" />
<input type="button" onclick="$('#myform').submit();" value="clickme" />
</form>
<script>
        $.validator.addMethod('mobilenumber', function (value) {
            if (value == null || value == '')
                return true;
            return /^04[0-9]{8}/.test(value);
        }, 'your mobile is invalid');

$("#myform").validate({
     rules:{
      'mobile' :{
        mobilenumber: true
      }
    }
});
$('input, textarea').placeholder();
</script>

The method would be fired when I clicked the submit button.

**Comment by erikmontes** [comment]
See https://github.com/mathiasbynens/jquery-placeholder/issues/66
