### ISSUE TITLE
Placeholder values erased when clicking any link on the page

### ISSUE THREAD

**Issue by chadwithuhc** [mathiasbynens/jquery-placeholder#250]
I've run into an error whenever I click a link on the page (for a Modal or expanding menu) all of the placeholder values on the page get erased. I can fix the problem if I comment out the following lines: https://github.com/mathiasbynens/jquery-placeholder/blob/bc98c214d6dbdf14f97d20e71b8269751c79b34b/jquery.placeholder.js#L114-L118

Is this necessary to have in there since we already have a form submit listener?

**Comment by amerikan** [comment]
Should be fix.
