### ISSUE TITLE
copytight years and lack of copyright statement/license in source

### ISSUE THREAD

**Issue by onlyjob** [mathiasbynens/jquery-placeholder#252]
* please add copyright years to `LICENSE-MIT.txt`;
* please include license and copyright statement to ` jquery.placeholder.js`.
Thanks.

**Comment by onlyjob** [comment]
Really? Just closing without explanation or resolution? :(

Proper grant of license and copyright statement are important...

**Comment by amerikan** [comment]
I've added it to the source file in comments as shown in this [commit](https://github.com/mathiasbynens/jquery-placeholder/commit/796ff35a0494568be645f4e4c5bcc1e8102c00db). In the read me there's a link to the MIT license, so I will not add a separate file.
