### ISSUE TITLE
Asp.net Posback issue

### ISSUE THREAD

**Issue by sebascomeau** [mathiasbynens/jquery-placeholder#253]
We notice in IE8 that if we do a postback with controls like checkbox and dropdownlist that the placeholder text become the textbox text. But this behavior is not present with linkbutton. However all asp.net controls that does a postback call the same javascript function __doPostBack(). We cannot figure why the behavior is different if the same function at the end is called. Thanks!

**Comment by amerikan** [comment]
@sebascomeau This seems to be a known issue. I've seen multiple people report it.

I'm rewriting this plugin, taking a different approach. Maybe you can try that one: https://github.com/amerikan/placeholder-polyfill
