### ISSUE TITLE
Disabled Input field not showing up as disabled

### ISSUE THREAD

**Issue by humblefools** [mathiasbynens/jquery-placeholder#256]
Hi,

I have some disabled input textboxes which have placeholder text. These get populated from database after page load, depending on previous textbox text. However these disabled boxes show up as active and user could change the text there.

Does some one have a fix for this ?

Thanks,
Humblefool

**Comment by amerikan** [comment]
I can't reproduce this. Please check out latest version of plugin and try to see if you have the same issue.
