### ISSUE TITLE
i9 and below multiple password issue

### ISSUE THREAD

**Issue by yangkennyk** [mathiasbynens/jquery-placeholder#263]
When you submit an empty form with multiple password inputs on ie9 and below, password inputs get filled in with the place holder text (except last one). 

when you click on those inputs and enter text the text is visible and the placeholder text doesn't go away

Here's a video of the issue in ie9

http://screencast.com/t/gGoW01Ns3qW

**Comment by amerikan** [comment]
@yangkennyk can't see the screenast as it's no longer available. Can you retest your case using v2.1.3?

**Comment by amerikan** [comment]
Closing for lack of response.

**Comment by yangkennyk** [comment]
didn't see the notification!

here's the video. 

http://www.screencast.com/users/BlueLeverageMedia/folders/Snagit/media/59ef167d-b497-4cfa-b678-cba037867d32

**Comment by yangkennyk** [comment]
although the bug may have been fixed here?

https://github.com/mathiasbynens/jquery-placeholder/issues/226
