### ISSUE TITLE
$("#theform").valid() 

### ISSUE THREAD

**Issue by Donzella** [mathiasbynens/jquery-placeholder#268]
This form gets submitted via jquery.form (ajaxsubmit) and is using jquery.validation. In IE 7, 8 , 9 the required fields do not fail validation as empty with the placeholder there when $("#theform").valid(); is called. I even added a method to the validation to check for notEqualTo the placeholder text and it still doesn't catch it. I am not sure what to do with this.

**Comment by amerikan** [comment]
@Donzella Haven't had time to look at this plugin lately, but will hopefully soon. For now you can try my other plugin https://github.com/amerikan/placeholder-polyfill which aims to solve same problem as this plugin, but taking a different approach.

**Comment by amerikan** [comment]
It's not going to work since this plugin is not compatible with jquery validation. See  #66
