### ISSUE TITLE
The plugin will not work when input(textarea) is hidden

### ISSUE THREAD

**Issue by animabear** [mathiasbynens/jquery-placeholder#283]
I check the source code and found this:

```javascript
placeholder = $.fn.placeholder = function(options) {
...
return this.filter((isInputSupported ? 'textarea' : ':input') + '[' + (debugMode ? 'placeholder-x' : 'placeholder') + ']')
                .not('.'+settings.customClass)
                .not(':radio, :checkbox, :hidden') // here
```

so if input or its ancestor element is hidden when init (it's a normal scene)，it won't work.

Could you tell me why use `:hidden` here ?  I make a small changes:

```javascript
.not(':radio, :checkbox, [type="hidden"]')
```

**Comment by amerikan** [comment]
@animabear you're right, `[type="hidden"]` should be used and not `:hidden`. If you can do a pull request I can merge, if not I can do it myself later.

**Comment by amerikan** [comment]
@animabear I have published a new release with this fix.

**Comment by animabear** [comment]
@amerikan   ok，thanks
