### ISSUE TITLE
lte IE9,it will be affected by <a href='javascript:;'>,the text will disappear

### ISSUE THREAD

**Issue by ccaaiime** [mathiasbynens/jquery-placeholder#290]
Is this a bug?
work on a weebox , when lte IE9,it will be affected by a href='javascript:;',the placeholder text will disappear!
ps.
i added a click event on A tag to show the weebox,when the weebox is showed, the placeholder text can't work

i had checked the releases, know that the author fixed this bug , but it still exist.

**Comment by huoyanwuzhe629** [comment]
I also met the same question, why?

**Comment by amerikan** [comment]
Feel free to fix the issue and do a pull request.

**Comment by andy199310** [comment]
Is this issue similar to #74 ?

**Comment by andy199310** [comment]
btw, I face another issue.
I use a tag's onclick event to open jquery-ui's dialog(shown as below), it will auto focus on the tag inside dialog. 

`<a href="javascript:void(0)" class="forget-password" onclick="$('#dialog-password').dialog('open');" >`

As a result, when plugin testing the **document.activeElement** won't get the a tag which has been click, it will get the element inside the dialog.

https://github.com/mathiasbynens/jquery-placeholder/blob/gh-pages/jquery.placeholder.js#L160

One solution is remove jquery-ui's auto focus function, is there another better solution?

Sorry about poor English, it isn't my native language :(
Thanks!

**Comment by cailingling** [comment]
I also met the same question,who can solve?

**Comment by moahmn** [comment]
@ccaaiime the problem is fixed?

**Comment by ccaaiime** [comment]
It's solved , fixed by  event.preventDefault()
