### ISSUE TITLE
How to interpret the licensing of version 2.0.7?

### ISSUE THREAD

**Issue by Maarten-Damen** [mathiasbynens/jquery-placeholder#299]
Hi,

Because of an old front-end version that is still available for backwards compatibility, we have an dependency on the jquery-placeholder version 2.0.7. This version was licensed under both MIT and GPL with the description "This plugin is dual licensed under the MIT and GPL licenses, just like jQuery itself.". 

Now there is and discussion how this should be interpreted. Should both license be applied or may we apply the license that suits our needs the best?

Thanks for helping out.

With kind regards,
Maarten

**Comment by amerikan** [comment]
@Maarten-Damen if that version has 2 licenses (multi-license) (https://en.wikipedia.org/wiki/Multi-licensing), you can typically choose the one you want to adhere to.
