### ISSUE TITLE
Update repo settings

### ISSUE THREAD

**Issue by amerikan** [mathiasbynens/jquery-placeholder#302]
Hello @mathiasbynens can you do the following on this repo:

1. Set 'master' as default branch
2. set github pages to 'master' branch in repo settings
3. delete gh-pages **AFTER** merging gh-pages to master

I think we had created gh-pages branch and set it as default a long time back since github at the time only allowed having pages from a gh-pages branch, which is no longer the case.

Thanks!

**Comment by amerikan** [comment]
Updated 3rd task.

**Comment by mathiasbynens** [comment]
Done.

**Comment by amerikan** [comment]
@mathiasbynens thanks!
