### ISSUE TITLE
Browser Back button (or history.back())  can break placeholder functionality (IE9)

### ISSUE THREAD

**Issue by sbull** [mathiasbynens/jquery-placeholder#58]
There are certain navigation scenarios that can cause placeholder to fail. The following is an example.

```html
<!DOCTYPE html>
<html>
  <head>
  <style>.placeholder { background-color:yellow; }</style>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="jquery.placeholder.js"></script>
    <script type="text/javascript">
if (window.location.search != '') { window.history.back(); }
$(function(){
  $('input[placeholder]').placeholder();
  $('#submit_link').click(function(){ $(this).closest('form').submit(); });
});
    </script>
  </head>
  <body>
<form action="#submitted" method="get">
Text1: <input type="text" name="txt1" placeholder="text holder"></input><br />
<a href="#submit" id="submit_link">SUBMIT</a>
</form>
  </body>
</html>
```

To see the bug, put this in a directory index file, and click on SUBMIT while the placeholder is displayed (submits form to same file with get parameters "?txt1="). This example automatically navigates "back" after the form submit, and the bug is seen.

You can also see this bug by removing the "window.history.back();" line and manually using the browser's back button.

**Comment by amerikan** [comment]
You would have to call .placeholder() again when coming and it should work.
