### ISSUE TITLE
Clicking on a input type"reset" will erase all textboxes with placeholders

### ISSUE THREAD

**Issue by erickgirard** [mathiasbynens/jquery-placeholder#83]
I don't know if it's the intended behavior but if you add an <input type"reset" /> in your page and click on it every textboxes will be reset to empty and all placeholders values will be erased.

If I test the behavior of a placeholder on a browser that supports placeholders, the values are reset but placeholder values remains still there.

Is there any workarounds ?

**Comment by chupetoide** [comment]
Hi guys, It also happends calling method reset()

**Comment by amerikan** [comment]
Though this behavior is not desired, it is based on the current implementation of the plugin. The plugin uses invisible input text fields to accomplish the placeholder holder effect. Clicking on a reset button will clear up the invisible input text fields that this plugin relies on. To fix this, it means rewriting this entire plugin. So either don't use a reset on the form or use my other plugin https://github.com/amerikan/placeholder-polyfill which solves the same problem, however, in a different manner.

**Comment by gaojing007** [comment]
I have the same problem,when call : $("#***Form").resetForm();
My solution  is :  
$('input,  textarea').removeClass("placeholder"); // remove placehodel class 
$('input,  textarea').placeholder();
