### ISSUE TITLE
PlaceHolder with jQuery .val

### ISSUE THREAD

**Issue by MetaEM** [mathiasbynens/jquery-placeholder#86]
Hi,
When setting a value with the jQuery .val('xxx') method on an input type password, the placeholder is not hidden.
this is due to the clone method that is not cloning data like ('placeholder-enabled').

The solution is simply to clone with data like this :
```js
try {
	$replacement = $input.clone(true).attr({ 'type': 'text' });
} catch(e) {
	$replacement = $('<input>').attr($.extend(args(this), { 'type': 'text' })).data('placeholder-enabled', true);
}
```

Best regards

**Comment by amerikan** [comment]
Very old issue, closing.
