### ISSUE TITLE
An unplaceholder() function would be really useful...

### ISSUE THREAD

**Issue by mohamedhafez** [mathiasbynens/jquery-placeholder#88]
I'm running into the extra password input causing problems with my client side validations, I'd like to undo the effects of calling placeholder whille i do that and submit, and then call placeholder() again after if theres an error preventing submission of the form... Just a suggestion, when i get time hopefully i'll be able to try to add it myself:) In the meantime anybody got suggestions to quickly work around this?

**Comment by amerikan** [comment]
Anyone feel free to implement this feature, I'm closing this.
