### ISSUE TITLE
Placeholder text not removed when dragging a value on IE 9

### ISSUE THREAD

**Issue by pparidans** [mathiasbynens/jquery-placeholder#93]
Today, I found out that the placeholder text is not removed when the user dragged and dropped a text value to the input field.

For example: 
```html
<input type="text" placeholder="Search" name="q">
```

Drag&Drop of a selected text "123456" results in the value "123456Search".

This issue occurred on IE 9 for Windows 7.

I still need to test for older version of IE.

**Comment by amerikan** [comment]
Very old issue, closing.
